### ISSUE TITLE
broken in aframe 0.3.0: Geometry transformation not applied

### ISSUE THREAD

**Issue by nylki** [nylki/aframe-fit-texture-component#4]

**Comment by jvgeee** [comment]
+1. Is this still being maintained?

**Comment by nylki** [comment]
@jascination If you do a PR I am happy to merge it. It's probably trivial to fix, but I have currently no time to investigate. However, I am actively monitoring for contributors to fix the problem :)

**Comment by nylki** [comment]
@jascination Ok, actually was pretty straightforward to fix it. :)
The event name `material-texture-loaded` got apparently renamed to `materialtextureloaded` in aframe 0.3.0.
