### ISSUE TITLE
MIME type error

### ISSUE THREAD

**Issue by sambshapiro** [nylki/aframe-fit-texture-component#5]
I'm getting the following error through browser installation:

`Refused to execute script from 'https://github.com/nylki/aframe-fit-texture-component/raw/master/dist/aframe-fit-texture-component.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

Any thoughts on how to fix?

**Comment by nylki** [comment]
Hi @sambshapiro!
It is recommended to download the file and embed it to your HTML.
It is a common problem that the MIME type of all raw files at github are `text/plain`. Some browsers (or browser versions) are strict and refuse to execute the script.

If you want to use an external script in your HTML, then you could use this link instead:
[https://unpkg.com/aframe-lsystem-component/dist/aframe-lsystem-component.min.js](https://unpkg.com/aframe-lsystem-component/dist/aframe-lsystem-component.min.js)
I updated the `README.md` to use the unpkg.com url in the examples for easier usage.

umpkg.com acts as a CDN server and delivers the proper MIME-types.
However I still recommend to download it directly or via npm if you want to use it in a production environment, for various reasons:

- reliability: unpkg.com may not be online forever or have outages
- security: in the end you can only be sure of the file content if you serve it from your own servers
